//
//  AlbumInteractor.swift
//  PicturePinch
//
//  Created by Danny Grob on 06/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlbumBusinessLogic
{
    func fetchAlbumContents(request: Albums.Contents.Request)
}

protocol AlbumDataStore
{
    
}

class AlbumInteractor: AlbumBusinessLogic, AlbumDataStore
{
    var presenter: AlbumPresentationLogic?
    var worker: AlbumWorker = AlbumWorker()
    
    func fetchAlbumContents(request: Albums.Contents.Request)
    {
        worker.fetchPictures(albumId: request.albumId, page: request.page, size: request.size) { [weak self] (result) in
            guard let self = self else {
                //TODO: error display present
                return
            }
            switch result {
            case .success(let pics):
                let response = Albums.Contents.Response(pictures: pics, hasMore: pics.count == request.size)
                self.presenter?.presentAlbumContents(response: response)
                break
            case .failure(_):
                //TODO: error display present
                break
            }
        }
        
        
    }
}
